apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: csi-dev
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: all-pvc
            mountPath: "/mnt/all-pv"
      volumes:
        - name: all-pvc
          persistentVolumeClaim:
            claimName: csi-demo-driver-pvc-01
