apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-csi-nginx-test
  namespace: default
  labels:
    app: demo-csi-nginx-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-csi-nginx-test
  template:
    metadata:
      labels:
        app: demo-csi-nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: all-pvc
            mountPath: "/mnt/all-pv"
      volumes:
        - name: all-pvc
          persistentVolumeClaim:
            claimName: demo-csi-driver-pvc
